#!/bin/bash
set -eu

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================

app=$YNH_APP_INSTANCE_NAME

final_path=$(ynh_app_setting_get $app final_path)
domain=$(ynh_app_setting_get $app domain)
rocketchat_version=$(ynh_app_setting_get $app rocketchat_version)
db_pwd=$(ynh_app_setting_get $app mysqlpwd)

#=================================================
# STANDARD BACKUP STEPS
#=================================================
# BACKUP THE APP MAIN DIR
#=================================================

ynh_backup "$final_path/rocket.chat-$rocketchat_version.gtar" "rocket.chat-$rocketchat_version.gtar"

#=================================================
# BACKUP THE NGINX CONFIGURATION
#=================================================

ynh_backup "/etc/nginx/conf.d/$domain.d/$app.conf" "nginx"

#=================================================
# BACKUP THE MONGODB DATABASE
#=================================================

sudo mongodump -o "./dump"
